### ISSUE TITLE
HTTP Client: URL Encoding is not supported

### ISSUE THREAD

**Issue by nahsh** [foundation-runtime/communication#31]
When trying to send special characters in the URL (e.g. slashes or spaces), the HTTP client throws exception. But when trying to use pre-encoded URLs, HTTP client re-encode the URL.

For example:
`GET http://host:1234/app/byId/1 2/3456` - cause exception
`GET http://host:1234/app/byId/1%202%2F3456` - changed to `http://host:1234/app/byId/1%25202%252F3456`, so the target server received it double encoded.

Please add support for pre-encoded URLs.

**Comment by yairogen** [comment]
https://groups.google.com/forum/#!topic/foundation-runtime-users/d__YXKoDqmk
