### ISSUE TITLE
HTTPClient - Allow adding query params from a map to the HttpRequest builder

### ISSUE THREAD

**Issue by SummerBulb** [foundation-runtime/communication#38]
Instead of builder.queryParams("key", val).queryParams("key2", val2)... I'd like to be able to do the following

map = {"key" -> val, "key2" -> val2}
builder.queryParams(map)

**Comment by yairogen** [comment]
The builder support Map using the MultiMap from Google:
HttpRequest.Builder queryParams(Multimap<String, String> queryParams)

**Comment by yairogen** [comment]
I see now this method is not public - so I'll expose it.
