### ISSUE TITLE
[Apache http client] Please update Deprecated X509HostNameVerifier 

### ISSUE THREAD

**Issue by bahirsch** [foundation-runtime/communication#84]
Please implement HostnameVerifier in lieu of X509HostNameVerifier

**Comment by yairogen** [comment]
What version are you using?

**Comment by bahirsch** [comment]
1.1.1-0

Bayla Hirsch

**Comment by yairogen** [comment]
you're out of date - I think this API was already replaced in later version. take a look at latest:
http://search.maven.org/#artifactdetails%7Ccom.cisco.oss.foundation%7Chttp-client-apache%7C1.2.2-1%7Cjar

**Comment by bahirsch** [comment]
Indeed working well after updating the client to the latest version

**Comment by bahirsch** [comment]
Indeed, working well after updating the version and some dependencies.
